In [7]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
from datasets import EmailEnron, EmailEnronFull, EmailEuFull, ContactHighSchool, ContactPrimarySchool, NDCClassesFull, TagsAskUbuntu, TagsMathSx, CongressBills, Cora, Citeseer
dataset = Cora()
incidence_matrix = dataset.incidence_matrix(lambda e: len(e) > 0)
print(dataset)

cora dataset: 4596 time steps, 1330 vertices, 1413 unique edges


In [9]:
from pymochy import Mochy, CommonNeighbors

In [10]:
%%time
mochy = Mochy(incidence_matrix)
mochy.count()

CPU times: user 5.25 s, sys: 0 ns, total: 5.25 s
Wall time: 1.07 s


array([     0,      0,    598, 383575,      0,     55,      0,     81,
        17806,  57249,     57,     95,    434,   1142,   1075,   3924,
           11,     35,     68,     74,      4,      9,   1264,   4224,
        55387, 319236,     15,    311,   1656,   3694])

In [11]:
len(mochy.count().nonzero()[0])

26

In [12]:
mochy.count().nonzero()

(array([ 2,  3,  5,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29]),)

In [ ]:
return

SyntaxError: 'return' outside function (3438313781.py, line 1)

In [ ]:
mochy.count().nonzero()

(array([ 2,  3,  5,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29]),)

In [ ]:
return

SyntaxError: 'return' outside function (3438313781.py, line 1)

In [ ]:
%%timeit -n 1 -r 10
mochy.count()

The slowest run took 5.58 times longer than the fastest. This could mean that an intermediate result is being cached.
2.46 µs ± 2.17 µs per loop (mean ± std. dev. of 10 runs, 1 loop each)


In [ ]:
np.array(mochy.count())

array([      0,       0,    8760,  763617,       0,   10462,       0,
         14208,  377170,  595238,    2419,   36166,   22929,  138727,
         34787,  115188,     420,    4793,   12239,    8176,     488,
         25489,   38620,  640173, 1231498, 5039842,    2081,   38222,
        112199,   67148])

In [ ]:
%time
np.array(mochy.count()).sum()

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 6.68 µs


9341059

In [ ]:
%time
motifs = mochy.sample(2, limit=10000)

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 6.2 µs
