In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [6]:
from datasets import EmailEnron, EmailEnronFull, EmailEuFull, ContactHighSchool, ContactPrimarySchool, NDCClassesFull, TagsAskUbuntu, TagsMathSx, CongressBills, Cora, Citeseer
dataset = Citeseer()
incidence_matrix = dataset.incidence_matrix(lambda e: len(e) > 0)
print(dataset)

citeseer dataset: 2805 time steps, 1019 vertices, 766 unique edges


In [ ]:
from pymochy import Mochy, CommonNeighbors

In [ ]:
%%time
mochy = Mochy(incidence_matrix)
mochy.count()

CPU times: user 1min 32s, sys: 183 ms, total: 1min 32s
Wall time: 5.93 s


array([       0,        0,    14573, 12824279,        0,     2079,
              0,      664,  1041202,  1787998,     8256,     3079,
          53668,    22286,    76958,    36074,     1754,     2569,
            995,      127,      669,       99,   417489,   169842,
       22509767, 30077175,    37949,   186715,   293546,   180255])

In [ ]:
len(mochy.count().nonzero()[0])

26

In [ ]:
list(mochy.count()[mochy.count().nonzero()])

[14573,
 12826553,
 2078,
 664,
 1041062,
 1787964,
 8252,
 3079,
 53653,
 22286,
 76958,
 36074,
 1754,
 2569,
 995,
 127,
 669,
 99,
 417489,
 169842,
 22509439,
 30077175,
 37939,
 186698,
 293559,
 180255]

In [ ]:
return

SyntaxError: 'return' outside function (3438313781.py, line 1)

In [ ]:
mochy.count().nonzero()

(array([ 2,  3,  5,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29]),)

In [ ]:
return

SyntaxError: 'return' outside function (3438313781.py, line 1)

In [ ]:
%%timeit -n 1 -r 10
mochy.count()

The slowest run took 5.58 times longer than the fastest. This could mean that an intermediate result is being cached.
2.46 µs ± 2.17 µs per loop (mean ± std. dev. of 10 runs, 1 loop each)


In [ ]:
np.array(mochy.count())

array([      0,       0,    8760,  763617,       0,   10462,       0,
         14208,  377170,  595238,    2419,   36166,   22929,  138727,
         34787,  115188,     420,    4793,   12239,    8176,     488,
         25489,   38620,  640173, 1231498, 5039842,    2081,   38222,
        112199,   67148])

In [ ]:
%time
np.array(mochy.count()).sum()

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 6.68 µs


9341059

In [ ]:
%time
motifs = mochy.sample(2, limit=10000)

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 6.2 µs
