In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
os.environ['OMP_NUM_THREADS'] = '32'

In [2]:
from datasets import EmailEnron, EmailEnronFull, EmailEuFull, ContactHighSchool, ContactPrimarySchool, NDCClassesFull, TagsAskUbuntu, TagsMathSx
dataset = ContactHighSchool()
incidence_matrix = dataset.incidence_matrix(lambda e: len(e) > 1)
print(dataset)

contact-high-school dataset: 172035 time steps, 328 vertices, 7818 unique edges


In [3]:
from pymochy import Mochy
from motif import motif_negative_sampling
from negative_sampling import NegativeSampler

In [4]:
mochy = Mochy(incidence_matrix)

In [5]:
incidence_matrix.shape

(328, 7818)

In [6]:
mochy.count()

array([       0,        0,    14573, 12828909,        0,     2079,
              0,      664,  1041280,  1788129,     8256,     3079,
          53668,    22286,    76958,    36074,     1754,     2569,
            995,      127,      669,       99,   417489,   169842,
       22513015, 30077175,    37964,   186778,   293608,   180255])

In [7]:
motifs = mochy.sample(29, limit=10000)[:, 1:]
motifs

array([[7331, 7542, 7658],
       [7261, 7715, 7735],
       [7185, 7221, 7498],
       ...,
       [   9, 2361, 5544],
       [   9,  296, 3437],
       [   9,  248, 5985]], dtype=int32)

In [8]:
ns = NegativeSampler(incidence_matrix, 0.5, 1)

In [9]:
ns

In [10]:
return

SyntaxError: 'return' outside function (3438313781.py, line 1)

In [ ]:
motif_negative_sampling(incidence_matrix, motifs, 0.5, 1)

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 1, 1, 1],
        [1, 0, 0, ..., 0, 0, 0]], dtype=int16),
 array([[10024, 15631, 20977],
        [ 2148,  4450,  4501],
        [ 1507,  4346, 15631],
        ...,
        [ 8235, 18633, 21666],
        [10736, 19567, 22319],
        [11586, 20179, 20654]], dtype=int32),
 array([[1.],
        [1.],
        [1.],
        ...,
        [0.],
        [0.],
        [0.]], dtype=float32),
 array([[1.],
        [1.],
        [1.],
        ...,
        [0.],
        [0.],
        [0.]], dtype=float32))

In [ ]:
motifs

array([[1396, 1398, 1436],
       [1387, 1400, 1447],
       [1382, 1420, 1436],
       ...,
       [   0, 1133, 1316],
       [   0,  931, 1133],
       [   0,  348, 1191]], dtype=int32)

In [ ]:
from motif import edge_motif_interactions, node_node_interactions

In [ ]:
nni = node_node_interactions(incidence_matrix)
eei = node_node_interactions(incidence_matrix.T)
emi = edge_motif_interactions(incidence_matrix, motifs)