In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
os.environ['OMP_NUM_THREADS'] = '128'

In [2]:
from datasets import EmailEnron, EmailEnronFull, EmailEuFull, ContactHighSchool, ContactPrimarySchool, NDCClassesFull, TagsAskUbuntu, TagsMathSx
dataset = EmailEnronFull()
incidence_matrix = dataset.incidence_matrix(lambda e: len(e) > 1)
print(dataset)

email-Enron-full dataset: 10885 time steps, 149 vertices, 1514 unique edges


In [3]:
from pymochy import Mochy
from motif import motif_negative_sampling
from negative_sampling import NegativeSampler

In [4]:
mochy = Mochy(incidence_matrix)

In [5]:
incidence_matrix.shape

(149, 1459)

In [6]:
mochy.count()

array([      0,       0,    8974,  772286,       0,   10851,       0,
         14951,  387607,  610733,    2419,   39782,   23289,  150986,
         35540,  122617,     420,    4898,   13273,    9577,     488,
         38346,   38824,  770822, 1244725, 5346318,    2078,   40162,
        119727,   71853])

In [7]:
motifs = mochy.sample(29, limit=10000)[:, 1:]
motifs

array([[1369, 1422, 1426],
       [1361, 1402, 1456],
       [1356, 1420, 1436],
       ...,
       [   0,  425,  732],
       [   0,  161, 1165],
       [   0,  161,  732]], dtype=int32)

In [8]:
ns = NegativeSampler(incidence_matrix, 0.5, 1)

In [9]:
ns

In [11]:
X_, motifs_, y_, z_ = motif_negative_sampling(incidence_matrix, motifs, 0.5, 1, mode="prob")

In [ ]:
motifs

array([[1422, 1426, 1432],
       [1409, 1436, 1440],
       [1387, 1400, 1447],
       ...,
       [   0,  583, 1191],
       [   0,  425, 1191],
       [   0,  161,  611]], dtype=int32)

In [ ]:
from motif import edge_motif_interactions, node_node_interactions

In [ ]:
nni = node_node_interactions(incidence_matrix)
eei = node_node_interactions(incidence_matrix.T)
emi = edge_motif_interactions(incidence_matrix, motifs)