In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
os.environ['OMP_NUM_THREADS'] = '128'

In [2]:
from datasets import EmailEnron, EmailEnronFull, EmailEuFull, ContactHighSchool, ContactPrimarySchool, NDCClassesFull, TagsAskUbuntu, TagsMathSx
dataset = EmailEnronFull()
incidence_matrix = dataset.incidence_matrix(lambda e: len(e) > 1)
print(dataset)

email-Enron-full dataset: 10885 time steps, 149 vertices, 1514 unique edges


In [3]:
from pymochy import Mochy
from motif import xmotif_negative_sampling, motif_negative_sampling

In [4]:
mochy = Mochy(incidence_matrix, False)

In [5]:
incidence_matrix.shape

(149, 1459)

In [6]:
mochy.count()

array([      0,       0,    8974,  773140,       0,   10860,       0,
         14951,  387607,  610733,    2419,   39782,   23289,  150986,
         35540,  122617,     420,    4898,   13273,    9577,     488,
         38346,   38824,  770822, 1245945, 5346318,    2081,   40210,
        119793,   71853])

In [7]:
motifs = mochy.sample(29, limit=10000)[:, 1:]
motifs

array([[1361, 1402, 1456],
       [1361, 1387, 1402],
       [1356, 1420, 1436],
       ...,
       [   1,  139,  223],
       [   0, 1165, 1316],
       [   0,  931, 1133]], dtype=int32)

In [8]:
d, n, e = xmotif_negative_sampling(incidence_matrix, motifs, 0.5, 1)

In [9]:
d

array([  0, 101,  77,  15,  44,  32,  44,  12,  58,  10,   0,  21,  37,
         7,   9,  18,   0,  49,  21,  13,  85,  15,  12,  94,  17,  29,
        10,  52,  26,  41,   7,   0,  16,  50,   6,   0,  33,  43,  14,
        25,  24, 117,  17,  60,  56,  81,  43,  41,  22,   2,   8,  50,
        27,  40,  28,  73,  38,  68,  23,  32,   9,  85,  61, 110,  27,
        78,  11,   6,  41,  28,  30,  22,  23,  19,  17,  25,  40,  33,
        27,  26,  25,   4,   7,   8,  17,  88,  36,  20,   8,   9,  29,
         8,   6,  53,   5,  31,  23,  54,  10,  24,   3,  12,  14,  10,
        52,   3,  16,  29,  67,  21,  22,  23,  64,  16,  52,  45,  70,
        57,  26,  14,  23,  16,  20,  12,   0,  75,   5,   8,  18,  36,
        28,  26,  63,  35,   3,  16,  50,  30,  63,   6,  63,  10,  22,
        17,  30,  24,  20,  35,  22])

In [10]:
n

array([[inf, inf, inf, ..., inf, inf, inf],
       [inf, inf,  1., ...,  3., inf, inf],
       [inf, inf, inf, ...,  3., inf, inf],
       ...,
       [inf, inf, inf, ..., inf, inf, inf],
       [inf, inf, inf, ..., inf, inf, inf],
       [inf, inf, inf, ..., inf, inf, inf]])

In [11]:
e 

array([[inf,  1.,  1., ..., inf, inf, inf],
       [inf,  3.,  3., ..., inf, inf, inf],
       [inf,  2.,  3., ..., inf, inf, inf],
       ...,
       [inf,  1.,  2., ..., inf, inf, inf],
       [inf,  1.,  1., ..., inf, inf, inf],
       [inf, inf, inf, ..., inf, inf, inf]])

In [12]:
return

SyntaxError: 'return' outside function (3438313781.py, line 1)

In [ ]:
motif_negative_sampling(incidence_matrix, motifs, 0.5, 1)

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 1, 0, 1],
        [1, 0, 0, ..., 0, 0, 0]], dtype=int16),
 array([[ 4928,  9641, 15500],
        [15500, 20862, 22169],
        [ 4042,  4396,  7971],
        ...,
        [ 1702, 10183, 14984],
        [  907, 10216, 14986],
        [10334, 20550, 20610]], dtype=int32),
 array([[1.],
        [1.],
        [1.],
        ...,
        [0.],
        [0.],
        [0.]], dtype=float32),
 array([[1.],
        [1.],
        [1.],
        ...,
        [0.],
        [0.],
        [0.]], dtype=float32))

In [ ]:
motifs

array([[1409, 1436, 1440],
       [1366, 1398, 1436],
       [1361, 1387, 1402],
       ...,
       [   0,   99, 1316],
       [   0,   99,  615],
       [   0,   63, 1191]], dtype=int32)

In [ ]:
from motif import edge_motif_interactions, node_node_interactions

In [ ]:
nni = node_node_interactions(incidence_matrix)
eei = node_node_interactions(incidence_matrix.T)
emi = edge_motif_interactions(incidence_matrix, motifs)