In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from datasets import EmailEnron, EmailEnronFull, EmailEuFull, ContactHighSchool, ContactPrimarySchool, NDCClassesFull, TagsAskUbuntu, TagsMathSx
dataset = EmailEnronFull()
incidence_matrix = dataset.incidence_matrix(lambda e: len(e) > 1)
print(dataset)

email-Enron-full dataset: 10885 time steps, 149 vertices, 1514 unique edges


In [3]:
from pymochy import Mochy
from motif import motif_negative_sampling

In [4]:
mochy = Mochy(incidence_matrix)

In [5]:
motifs = mochy.sample(29, limit=50000)[:, 1:]
motifs

array([[1436, 1440, 1443],
       [1422, 1426, 1449],
       [1422, 1426, 1432],
       ...,
       [   0,   99, 1316],
       [   0,   99,  615],
       [   0,   63, 1191]], dtype=int32)

In [6]:
im, motifs, ye, ym = motif_negative_sampling(incidence_matrix, motifs, 0.5, 1)

Elapsed time:  0.023288726806640625


In [7]:
motifs

array([[ 1557, 32545, 57997],
       [ 4085,  8951,  9830],
       [ 4085,  8951,  9824],
       ...,
       [ 5355, 15681, 84074],
       [ 3614, 34826, 38637],
       [18066, 35420, 74659]], dtype=int32)

In [8]:
from motif import compute_edge_indexes

In [9]:
nni, eei, emi = compute_edge_indexes(im, motifs, edge_threshold=4)

In [10]:
nni

array([[  1,   2,   1, ..., 148, 147, 148],
       [  2,   1,   3, ..., 145, 148, 147]], dtype=int32)