In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
os.environ['OMP_NUM_THREADS'] = '128'

In [2]:
from datasets import EmailEnron, EmailEnronFull, EmailEuFull, ContactHighSchool, ContactPrimarySchool, NDCClassesFull, TagsAskUbuntu, TagsMathSx
dataset = ContactHighSchool()
incidence_matrix = dataset.incidence_matrix(lambda e: len(e) > 1)
print(dataset)

contact-high-school dataset: 172035 time steps, 328 vertices, 7818 unique edges


In [3]:
from pymochy import Mochy
from motif import xmotif_negative_sampling

In [4]:
mochy = Mochy(incidence_matrix)

In [5]:
incidence_matrix.shape

(328, 7818)

In [6]:
mochy.count()

In [ ]:
motifs = mochy.sample(29, limit=50000)[:, 1:]
motifs

array([[1422, 1426, 1449],
       [1420, 1436, 1449],
       [1411, 1423, 1436],
       ...,
       [   0,   99, 1316],
       [   0,   99,  931],
       [   0,   99,  615]], dtype=int32)

In [ ]:
xmotif_negative_sampling(incidence_matrix, motifs, 0.5, 1)

In [ ]:
incidence_matrix.nonzero()

(array([  1,   1,   1, ..., 148, 148, 148]),
 array([  24,   46,   61, ..., 1163, 1411, 1423]))

In [ ]:
motifs

array([[1422, 1426, 1449],
       [1420, 1436, 1449],
       [1411, 1423, 1436],
       ...,
       [   0,   99, 1316],
       [   0,   99,  931],
       [   0,   99,  615]], dtype=int32)

In [ ]:
from motif import edge_motif_interactions, node_node_interactions

In [ ]:
nni = node_node_interactions(incidence_matrix)
eei = node_node_interactions(incidence_matrix.T)
emi = edge_motif_interactions(incidence_matrix, motifs)