In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
os.environ['OMP_NUM_THREADS'] = '16'

In [2]:
from datasets import EmailEnron, EmailEnronFull, EmailEuFull, ContactHighSchool, ContactPrimarySchool, NDCClassesFull, TagsAskUbuntu, TagsMathSx
dataset = EmailEnronFull()
incidence_matrix = dataset.incidence_matrix(lambda e: len(e) > 1)
print(dataset)

email-Enron-full dataset: 10885 time steps, 149 vertices, 1514 unique edges


In [3]:
from pymochy import Mochy
from motif import xmotif_negative_sampling

In [4]:
mochy = Mochy(incidence_matrix)

In [5]:
incidence_matrix.shape

(149, 1459)

In [6]:
mochy.count()

array([      0,       0,    8969,  772960,       0,   10802,       0,
         14916,  387154,  610322,    2416,   39700,   23269,  150765,
         35517,  122502,     420,    4898,   13273,    9577,     488,
         38346,   38824,  770822, 1245945, 5346318,    2081,   40210,
        119793,   71853])

In [7]:
motifs = mochy.sample(29, limit=25000)[:, 1:]
motifs

array([[1422, 1426, 1449],
       [1420, 1436, 1449],
       [1409, 1436, 1440],
       ...,
       [   0,  425,  732],
       [   0,  348, 1191],
       [   0,  161, 1165]], dtype=int32)

In [9]:
im, motifs, ye, ym = xmotif_negative_sampling(incidence_matrix, motifs, 0.5, 1)

TypeError: cannot unpack non-iterable NoneType object

In [ ]:
incidence_matrix.nonzero()

(array([  1,   1,   1, ..., 148, 148, 148]),
 array([  24,   46,   61, ..., 1163, 1411, 1423]))

In [ ]:
motifs

array([[ 2510,  5457,  6034],
       [ 2512,  6038, 32876],
       [ 8222, 12586, 32876],
       ...,
       [ 7106,  7125, 20579],
       [ 1460,  7126, 38660],
       [ 5391, 11088, 43635]], dtype=int32)

In [ ]:
from motif import edge_motif_interactions, node_node_interactions

In [ ]:
nni = node_node_interactions(incidence_matrix)
eei = node_node_interactions(incidence_matrix.T)
emi = edge_motif_interactions(incidence_matrix, motifs)