In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
os.environ['OMP_NUM_THREADS'] = '32'

In [2]:
from datasets import EmailEnron, EmailEnronFull, EmailEuFull, ContactHighSchool, ContactPrimarySchool, NDCClassesFull, TagsAskUbuntu, TagsMathSx
dataset = ContactHighSchool()
incidence_matrix = dataset.incidence_matrix(lambda e: len(e) > 1)
print(dataset)

contact-high-school dataset: 172035 time steps, 328 vertices, 7818 unique edges


In [3]:
from pymochy import Mochy
from motif import motif_negative_sampling
from negative_sampling import NegativeSampler

In [4]:
mochy = Mochy(incidence_matrix)

In [5]:
incidence_matrix.shape

(328, 7818)

In [6]:
mochy.count()

array([       0,        0,    14573, 12828909,        0,     2079,
              0,      664,  1039692,  1785070,     8244,     3075,
          53668,    22286,    76958,    36074,     1754,     2569,
            995,      127,      669,       99,   417489,   169842,
       22513015, 30077175,    37964,   186778,   293608,   180255])

In [7]:
motifs = mochy.sample(29, limit=10000)[:, 1:]
motifs

array([[7364, 7440, 7675],
       [7272, 7323, 7364],
       [7255, 7364, 7675],
       ...,
       [   9,  627, 6452],
       [   9,  296, 2741],
       [   9,  174, 7069]], dtype=int32)

In [8]:
ns = NegativeSampler(incidence_matrix, 0.5, 1)

In [9]:
ns

In [14]:
motif_negative_sampling(incidence_matrix, motifs, 0.5, 1)

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int16),
 array([[ 3312, 16801, 16825],
        [16825, 16878, 16981],
        [ 3315, 16801, 16825],
        ...,
        [ 4774, 15339, 15581],
        [ 7871,  8033, 10251],
        [ 3445,  4751,  8165]], dtype=int32),
 array([[1.],
        [1.],
        [1.],
        ...,
        [0.],
        [1.],
        [1.]], dtype=float32),
 array([[1.],
        [1.],
        [1.],
        ...,
        [0.],
        [0.],
        [0.]], dtype=float32))

In [11]:
motifs

array([[7364, 7440, 7675],
       [7272, 7323, 7364],
       [7255, 7364, 7675],
       ...,
       [   9,  627, 6452],
       [   9,  296, 2741],
       [   9,  174, 7069]], dtype=int32)

In [12]:
from motif import edge_motif_interactions, node_node_interactions

In [13]:
nni = node_node_interactions(incidence_matrix)
eei = node_node_interactions(incidence_matrix.T)
emi = edge_motif_interactions(incidence_matrix, motifs)