In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
os.environ['OMP_NUM_THREADS'] = '128'

In [2]:
from datasets import EmailEnron, EmailEnronFull, EmailEuFull, ContactHighSchool, ContactPrimarySchool, NDCClassesFull, TagsAskUbuntu, TagsMathSx
dataset = EmailEnronFull()
incidence_matrix = dataset.incidence_matrix(lambda e: len(e) > 1)
print(dataset)

email-Enron-full dataset: 10885 time steps, 149 vertices, 1514 unique edges


In [3]:
from pymochy import Mochy
from motif import motif_negative_sampling
from negative_sampling import NegativeSampler

In [4]:
mochy = Mochy(incidence_matrix)

In [5]:
incidence_matrix.shape

(149, 1459)

In [6]:
mochy.count()

array([      0,       0,    8970,  773102,       0,   10858,       0,
         14926,  387607,  610733,    2419,   39782,   23289,  150986,
         35540,  122617,     420,    4898,   13273,    9577,     488,
         38346,   38824,  770822, 1245614, 5346318,    2081,   40210,
        119793,   71853])

In [7]:
motifs = mochy.sample(29, limit=10000)[:, 1:]
motifs

array([[1396, 1398, 1421],
       [1374, 1387, 1400],
       [1369, 1422, 1426],
       ...,
       [   1,  139,  439],
       [   0,  611,  732],
       [   0,   99,  931]], dtype=int32)

In [8]:
ns = NegativeSampler(incidence_matrix, 0.5, 1)

In [9]:
ns

In [10]:
motif_negative_sampling(incidence_matrix, motifs, 0.5, 1)

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 1, 0, 0]], dtype=int16),
 array([[ 9969, 20720, 20800],
        [ 1648,  4379,  4422],
        [ 1456,  2921,  4261],
        ...,
        [ 1509,  3247, 11538],
        [ 6220, 16658, 17655],
        [ 7344, 10287, 20438]], dtype=int32),
 array([[1.],
        [1.],
        [1.],
        ...,
        [0.],
        [0.],
        [0.]], dtype=float32),
 array([[1.],
        [1.],
        [1.],
        ...,
        [0.],
        [0.],
        [0.]], dtype=float32))

In [11]:
motifs

array([[1396, 1398, 1421],
       [1374, 1387, 1400],
       [1369, 1422, 1426],
       ...,
       [   1,  139,  439],
       [   0,  611,  732],
       [   0,   99,  931]], dtype=int32)

In [12]:
from motif import edge_motif_interactions, node_node_interactions

In [13]:
nni = node_node_interactions(incidence_matrix)
eei = node_node_interactions(incidence_matrix.T)
emi = edge_motif_interactions(incidence_matrix, motifs)