In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
os.environ['OMP_NUM_THREADS'] = '32'

In [2]:
from datasets import EmailEnron, EmailEnronFull, EmailEuFull, ContactHighSchool, ContactPrimarySchool, NDCClassesFull, TagsAskUbuntu, TagsMathSx
dataset = EmailEnronFull()
incidence_matrix = dataset.incidence_matrix(lambda e: len(e) > 1)
print(dataset)

email-Enron-full dataset: 10885 time steps, 149 vertices, 1514 unique edges


In [3]:
from pymochy import Mochy
from motif import motif_negative_sampling
from negative_sampling import NegativeSampler

In [4]:
mochy = Mochy(incidence_matrix)

In [5]:
incidence_matrix.shape

(149, 1459)

In [22]:
mochy.count()

array([      0,       0,    8971,  772548,       0,   10858,       0,
         14950,  387607,  610733,    2419,   39767,   23289,  150979,
         35540,  122617,     420,    4898,   13273,    9577,     488,
         38346,   38824,  770822, 1245096, 5346318,    2077,   40193,
        119762,   71853])

In [7]:
motifs = mochy.sample(29, limit=10000)[:, 1:]
motifs

array([[1361, 1402, 1456],
       [1351, 1396, 1398],
       [1332, 1361, 1456],
       ...,
       [   1,  257,  624],
       [   1,  257,  301],
       [   0,  931, 1133]], dtype=int32)

In [8]:
ns = NegativeSampler(incidence_matrix, 0.5, 1)

In [9]:
ns

In [10]:
motif_negative_sampling(incidence_matrix, motifs, 0.5, 1)

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0]], dtype=int16),
 array([[ 4068,  4528,  7972],
        [ 9844, 11549, 20651],
        [ 4108,  4528,  7972],
        ...,
        [ 5321,  6499, 16533],
        [ 4706, 16619, 20430],
        [ 8819, 18367, 21405]], dtype=int32),
 array([[1.],
        [1.],
        [1.],
        ...,
        [0.],
        [0.],
        [0.]], dtype=float32),
 array([[1.],
        [1.],
        [1.],
        ...,
        [0.],
        [0.],
        [0.]], dtype=float32))

In [11]:
motifs

array([[1361, 1402, 1456],
       [1351, 1396, 1398],
       [1332, 1361, 1456],
       ...,
       [   1,  257,  624],
       [   1,  257,  301],
       [   0,  931, 1133]], dtype=int32)

In [12]:
from motif import edge_motif_interactions, node_node_interactions

In [13]:
nni = node_node_interactions(incidence_matrix)
eei = node_node_interactions(incidence_matrix.T)
emi = edge_motif_interactions(incidence_matrix, motifs)