In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
os.environ['OMP_NUM_THREADS'] = '16'

In [2]:
from datasets import EmailEnron, EmailEnronFull, EmailEuFull, ContactHighSchool, ContactPrimarySchool, NDCClassesFull, TagsAskUbuntu, TagsMathSx
dataset = EmailEnronFull()
incidence_matrix = dataset.incidence_matrix(lambda e: len(e) > 1)
print(dataset)

email-Enron-full dataset: 10885 time steps, 149 vertices, 1514 unique edges


In [3]:
from pymochy import Mochy
from motif import motif_negative_sampling

In [4]:
mochy = Mochy(incidence_matrix)

In [5]:
incidence_matrix.shape

(149, 1459)

In [6]:
mochy.count()

array([      0,       0,    8974,  773140,       0,   10860,       0,
         14951,  387607,  610733,    2419,   39782,   23289,  150986,
         35540,  122617,     420,    4898,   13273,    9577,     488,
         38346,   38824,  770822, 1245945, 5346318,    2081,   40210,
        119793,   71853])

In [7]:
motifs = mochy.sample(29, limit=25000)[:, 1:]
motifs

here


array([[1436, 1440, 1443],
       [1420, 1436, 1449],
       [1409, 1436, 1440],
       ...,
       [   0,  425,  732],
       [   0,  348, 1191],
       [   0,  161, 1165]], dtype=int32)

In [8]:
im, motifs, ye, ym = motif_negative_sampling(incidence_matrix, motifs, 0.5, 1)

Elapsed time:  0.046607255935668945


In [9]:
motifs

array([[ 1100, 19433, 33236],
       [ 2626,  6153, 33236],
       [ 9283, 19433, 33236],
       ...,
       [ 7235,  7250, 20671],
       [ 7251,  9401, 35672],
       [20625, 21675, 46576]], dtype=int32)

In [10]:
from motif import edge_motif_interactions, node_node_interactions

In [ ]:
nni = node_node_interactions(incidence_matrix)
eei = node_node_interactions(incidence_matrix.T)
emi = edge_motif_interactions(incidence_matrix, motifs)

Elapsed time:  0.4053325653076172


In [ ]:
nni

array([[  1,   2,   1, ..., 148, 147, 148],
       [  2,   1,   4, ..., 145, 148, 147]], dtype=int32)